# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/vchs/Sources/Repos/Relanotes/relacalc/qtdesign_ui/calculator_window.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(717, 413)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/icons/window_icons/calculator.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.labelClearHistory = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.labelClearHistory.setFont(font)
        self.labelClearHistory.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.labelClearHistory.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelClearHistory.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelClearHistory.setObjectName("labelClearHistory")
        self.horizontalLayout_2.addWidget(self.labelClearHistory)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setStyleSheet("background-color: rgb(220, 220, 220);")
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_4.setSpacing(16)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.textEdit.setFont(font)
        self.textEdit.setAcceptRichText(False)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_5.addWidget(self.textEdit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelFormula = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelFormula.setFont(font)
        self.labelFormula.setObjectName("labelFormula")
        self.horizontalLayout.addWidget(self.labelFormula)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.labelResult = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.labelResult.setFont(font)
        self.labelResult.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.labelResult.setStyleSheet("")
        self.labelResult.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelResult.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.labelResult.setObjectName("labelResult")
        self.horizontalLayout.addWidget(self.labelResult)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 10, 10, 10)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_2.addWidget(self.lineEdit_2)
        self.labelComment = QtWidgets.QLabel(Dialog)
        self.labelComment.setObjectName("labelComment")
        self.verticalLayout_2.addWidget(self.labelComment)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_3.addWidget(self.pushButton)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.buttonAdd_to_note = QtWidgets.QPushButton(Dialog)
        self.buttonAdd_to_note.setObjectName("buttonAdd_to_note")
        self.verticalLayout_4.addWidget(self.buttonAdd_to_note)
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_4.addWidget(self.label_7)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setMinimumSize(QtCore.QSize(114, 0))
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.chbTabToPlus = QtWidgets.QCheckBox(self.groupBox)
        self.chbTabToPlus.setGeometry(QtCore.QRect(0, 20, 111, 23))
        self.chbTabToPlus.setChecked(True)
        self.chbTabToPlus.setObjectName("chbTabToPlus")
        self.chbNewlineToPlus = QtWidgets.QCheckBox(self.groupBox)
        self.chbNewlineToPlus.setGeometry(QtCore.QRect(0, 40, 111, 23))
        self.chbNewlineToPlus.setChecked(True)
        self.chbNewlineToPlus.setObjectName("chbNewlineToPlus")
        self.chbSpaceToPlus = QtWidgets.QCheckBox(self.groupBox)
        self.chbSpaceToPlus.setGeometry(QtCore.QRect(0, 60, 111, 23))
        self.chbSpaceToPlus.setObjectName("chbSpaceToPlus")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(0, 120, 111, 18))
        self.label_4.setObjectName("label_4")
        self.chbRemoveText = QtWidgets.QCheckBox(self.groupBox)
        self.chbRemoveText.setGeometry(QtCore.QRect(0, 80, 111, 23))
        self.chbRemoveText.setChecked(True)
        self.chbRemoveText.setObjectName("chbRemoveText")
        self.rbDontChangeDecimalPoint = QtWidgets.QRadioButton(self.groupBox)
        self.rbDontChangeDecimalPoint.setGeometry(QtCore.QRect(0, 140, 106, 23))
        self.rbDontChangeDecimalPoint.setChecked(False)
        self.rbDontChangeDecimalPoint.setObjectName("rbDontChangeDecimalPoint")
        self.rbRemoveDecimalPoint = QtWidgets.QRadioButton(self.groupBox)
        self.rbRemoveDecimalPoint.setGeometry(QtCore.QRect(0, 160, 106, 23))
        self.rbRemoveDecimalPoint.setChecked(True)
        self.rbRemoveDecimalPoint.setObjectName("rbRemoveDecimalPoint")
        self.rbDecimalPointMakeDot = QtWidgets.QRadioButton(self.groupBox)
        self.rbDecimalPointMakeDot.setGeometry(QtCore.QRect(0, 180, 121, 23))
        self.rbDecimalPointMakeDot.setObjectName("rbDecimalPointMakeDot")
        self.horizontalLayout_4.addWidget(self.groupBox)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "RelaCalc"))
        self.label_5.setText(_translate("Dialog", "History:"))
        self.labelClearHistory.setText(_translate("Dialog", "<html><head/><body><p><a href=\"clear_history\"><span style=\" text-decoration: underline; color:#004455;\">Clear History</span></a></p></body></html>"))
        self.label.setText(_translate("Dialog", "Type an expression or insert text:"))
        self.labelFormula.setText(_translate("Dialog", "TextLabel"))
        self.label_2.setText(_translate("Dialog", "="))
        self.labelResult.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#000000;\">TextLabel</span></p></body></html>"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p>Some things about format: <span style=\" font-size:12pt; font-weight:600; color:#008066;\">*</span> multiplication, <span style=\" font-size:12pt; font-weight:600; color:#008066;\">/</span> division. Any other operations avalaible too. Decimal sign is a dot <span style=\" font-size:12pt; font-weight:600; color:#008066;\">.</span></p></body></html>"))
        self.labelComment.setText(_translate("Dialog", "Your comment for history"))
        self.pushButton.setText(_translate("Dialog", "Add to history"))
        self.label_6.setText(_translate("Dialog", "--"))
        self.buttonAdd_to_note.setText(_translate("Dialog", "Add to note"))
        self.label_7.setText(_translate("Dialog", "--"))
        self.groupBox.setTitle(_translate("Dialog", "Options"))
        self.chbTabToPlus.setText(_translate("Dialog", "tab → +"))
        self.chbNewlineToPlus.setText(_translate("Dialog", "newline → +"))
        self.chbSpaceToPlus.setText(_translate("Dialog", "space → +"))
        self.label_4.setText(_translate("Dialog", "Operation with \",\":"))
        self.chbRemoveText.setText(_translate("Dialog", "Remove text"))
        self.rbDontChangeDecimalPoint.setText(_translate("Dialog", "Don`t change"))
        self.rbRemoveDecimalPoint.setText(_translate("Dialog", "Remove \",\""))
        self.rbDecimalPointMakeDot.setText(_translate("Dialog", ", → . (decimal)"))

from resources import resources_rc
